# Generated by Django 4.1.2 on 2022-10-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='pending', max_length=50, null=True),
        ),
    ]
